### ISSUE TITLE
Error on Run

### ISSUE THREAD

**Issue by apexfinity** [IzK-ArcOS/ArcOS-API-Rewritten#11]
This error comes up whenever trying to run `main.py`

```shell
C:\Users\%username%\Downloads\ArcOS-API-Rewritten-api-v2\ArcOS-API-Rewritten-api-v2>python main.py
Traceback (most recent call last):
  File "C:\Users\%username%\Downloads\ArcOS-API-Rewritten-api-v2\ArcOS-API-Rewritten-api-v2\main.py", line 5, in <module>
    import arcos_backend
  File "C:\Users\%username%\Downloads\ArcOS-API-Rewritten-api-v2\ArcOS-API-Rewritten-api-v2\arcos_backend\__init__.py", line 12, in <module>
    from .routers import TAGS_DOCS
  File "C:\Users\%username%\Downloads\ArcOS-API-Rewritten-api-v2\ArcOS-API-Rewritten-api-v2\arcos_backend\routers\__init__.py", line 1, in <module>
    from enum import StrEnum
ImportError: cannot import name 'StrEnum' from 'enum' (C:\Users\%username%\AppData\Local\Programs\Python\Python310\lib\enum.py)
``` 
Installed using requirements.txt and even ran `pip3 install -U enum34`, however, it doesnt work.

**Comment by nulqwy** [comment]
...what python version have you got? thats a builtin module

**Comment by nulqwy** [comment]
ok i figured from logs it is 3.10, please update to at least 3.11

**Comment by apexfinity** [comment]
> ok i figured from logs it is 3.10, please update to at least 3.11

okay thank you!

**Comment by nulqwy** [comment]
...did that resolve it?

**Comment by apexfinity** [comment]
yes
