### ISSUE TITLE
`user/create` fails with 500 if the template directory doesn't exist

### ISSUE THREAD

**Issue by IzKuipers** [IzK-ArcOS/ArcOS-API-Rewritten#2]
It creates the user, but still ends the request with a 500 because it can't find the `data/template` directory. The logs are as follows:

```
Aug 11 13:35:03: INFO:     <IPv6 removed> - "GET /user/create?ac=ac97322c-ad70& HTTP/1.0" 500 Internal Server Error
Aug 11 13:35:03: ERROR:    Exception in ASGI application
Aug 11 13:35:03: Traceback (most recent call last):
Aug 11 13:35:03:   File "/usr/lib/python3/dist-packages/anyio/streams/memory.py", line 98, in receive
Aug 11 13:35:03:     return self.receive_nowait()
Aug 11 13:35:03:            ^^^^^^^^^^^^^^^^^^^^^
Aug 11 13:35:03:   File "/usr/lib/python3/dist-packages/anyio/streams/memory.py", line 93, in receive_nowait
Aug 11 13:35:03:     raise WouldBlock
Aug 11 13:35:03: anyio.WouldBlock
Aug 11 13:35:03: During handling of the above exception, another exception occurred:
Aug 11 13:35:03: Traceback (most recent call last):
Aug 11 13:35:03:   File "/usr/local/lib/python3.11/dist-packages/starlette/middleware/base.py", line 78, in call_next
Aug 11 13:35:03:     message = await recv_stream.receive()
Aug 11 13:35:03:               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
Aug 11 13:35:03:   File "/usr/lib/python3/dist-packages/anyio/streams/memory.py", line 118, in receive
Aug 11 13:35:03:     raise EndOfStream
Aug 11 13:35:03: anyio.EndOfStream
Aug 11 13:35:03: During handling of the above exception, another exception occurred:
Aug 11 13:35:03: Traceback (most recent call last):
Aug 11 13:35:03:   File "/home/devapi/.local/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 428, in run_asgi
Aug 11 13:35:03:     result = await app(  # type: ignore[func-returns-value]
Aug 11 13:35:03:              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Aug 11 13:35:03:   File "/home/devapi/.local/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
Aug 11 13:35:03:     return await self.app(scope, receive, send)
Aug 11 13:35:03:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Aug 11 13:35:03:   File "/home/devapi/.local/lib/python3.11/site-packages/fastapi/applications.py", line 289, in __call__
Aug 11 13:35:03:     await super().__call__(scope, receive, send)
Aug 11 13:35:03:   File "/usr/local/lib/python3.11/dist-packages/starlette/applications.py", line 122, in __call__
Aug 11 13:35:03:     await self.middleware_stack(scope, receive, send)
Aug 11 13:35:03:   File "/usr/local/lib/python3.11/dist-packages/starlette/middleware/errors.py", line 184, in __call__
Aug 11 13:35:03:     raise exc
Aug 11 13:35:03:   File "/usr/local/lib/python3.11/dist-packages/starlette/middleware/errors.py", line 162, in __call__
Aug 11 13:35:03:     await self.app(scope, receive, _send)
Aug 11 13:35:03:   File "/usr/local/lib/python3.11/dist-packages/starlette/middleware/base.py", line 108, in __call__
Aug 11 13:35:03:     response = await self.dispatch_func(request, call_next)
Aug 11 13:35:03:                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Aug 11 13:35:03:   File "/home/devapi/ArcOS-API-Rewritten/arcos_backend/authentication.py", line 24, in dispatch
Aug 11 13:35:03:     return await call_next(request)
Aug 11 13:35:03:            ^^^^^^^^^^^^^^^^^^^^^^^^
Aug 11 13:35:03:   File "/usr/local/lib/python3.11/dist-packages/starlette/middleware/base.py", line 84, in call_next
Aug 11 13:35:03:     raise app_exc
Aug 11 13:35:03:   File "/usr/local/lib/python3.11/dist-packages/starlette/middleware/base.py", line 70, in coro
Aug 11 13:35:03:     await self.app(scope, receive_or_disconnect, send_no_error)
Aug 11 13:35:03:   File "/usr/local/lib/python3.11/dist-packages/starlette/middleware/cors.py", line 91, in __call__
Aug 11 13:35:03:     await self.simple_response(scope, receive, send, request_headers=headers)
Aug 11 13:35:03:   File "/usr/local/lib/python3.11/dist-packages/starlette/middleware/cors.py", line 146, in simple_response
Aug 11 13:35:03:     await self.app(scope, receive, send)
Aug 11 13:35:03:   File "/usr/local/lib/python3.11/dist-packages/starlette/middleware/exceptions.py", line 79, in __call__
Aug 11 13:35:03:     raise exc
Aug 11 13:35:03:   File "/usr/local/lib/python3.11/dist-packages/starlette/middleware/exceptions.py", line 68, in __call__
Aug 11 13:35:03:     await self.app(scope, receive, sender)
Aug 11 13:35:03:   File "/home/devapi/.local/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
Aug 11 13:35:03:     raise e
Aug 11 13:35:03:   File "/home/devapi/.local/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
Aug 11 13:35:03:     await self.app(scope, receive, send)
Aug 11 13:35:03:   File "/usr/local/lib/python3.11/dist-packages/starlette/routing.py", line 718, in __call__
Aug 11 13:35:03:     await route.handle(scope, receive, send)
Aug 11 13:35:03:   File "/usr/local/lib/python3.11/dist-packages/starlette/routing.py", line 276, in handle
Aug 11 13:35:03:     await self.app(scope, receive, send)
Aug 11 13:35:03:   File "/usr/local/lib/python3.11/dist-packages/starlette/routing.py", line 66, in app
Aug 11 13:35:03:     response = await func(request)
Aug 11 13:35:03:                ^^^^^^^^^^^^^^^^^^^
Aug 11 13:35:03:   File "/home/devapi/.local/lib/python3.11/site-packages/fastapi/routing.py", line 273, in app
Aug 11 13:35:03:     raw_response = await run_endpoint_function(
Aug 11 13:35:03:                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Aug 11 13:35:03:   File "/home/devapi/.local/lib/python3.11/site-packages/fastapi/routing.py", line 192, in run_endpoint_function
Aug 11 13:35:03:     return await run_in_threadpool(dependant.call, **values)
Aug 11 13:35:03:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Aug 11 13:35:03:   File "/usr/local/lib/python3.11/dist-packages/starlette/concurrency.py", line 41, in run_in_threadpool
Aug 11 13:35:03:     return await anyio.to_thread.run_sync(func, *args)
Aug 11 13:35:03:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Aug 11 13:35:03:   File "/usr/lib/python3/dist-packages/anyio/to_thread.py", line 33, in run_sync
Aug 11 13:35:03:     return await get_asynclib().run_sync_in_worker_thread(
Aug 11 13:35:03:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Aug 11 13:35:03:   File "/usr/lib/python3/dist-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
Aug 11 13:35:03:     return await future
Aug 11 13:35:03:            ^^^^^^^^^^^^
Aug 11 13:35:03:   File "/usr/lib/python3/dist-packages/anyio/_backends/_asyncio.py", line 807, in run
Aug 11 13:35:03:     result = context.run(func, *args)
Aug 11 13:35:03:              ^^^^^^^^^^^^^^^^^^^^^^^^
Aug 11 13:35:03:   File "/home/devapi/ArcOS-API-Rewritten/arcos_backend/routers/v1/user.py", line 32, in user_create
Aug 11 13:35:03:     Userspace(fs, user.id)
Aug 11 13:35:03:   File "/home/devapi/ArcOS-API-Rewritten/arcos_backend/filesystem/userspace.py", line 22, in __init__
Aug 11 13:35:03:     self.deploy_template('.')
Aug 11 13:35:03:   File "/home/devapi/ArcOS-API-Rewritten/arcos_backend/filesystem/userspace.py", line 83, in deploy_template
Aug 11 13:35:03:     self._fs.deploy_template(self._path_id.joinpath(path))
Aug 11 13:35:03:   File "/home/devapi/ArcOS-API-Rewritten/arcos_backend/filesystem/__init__.py", line 94, in deploy_template
Aug 11 13:35:03:     shutil.copy(self._template, self._root.joinpath(path))
Aug 11 13:35:03:   File "/usr/lib/python3.11/shutil.py", line 419, in copy
Aug 11 13:35:03:     copyfile(src, dst, follow_symlinks=follow_symlinks)
Aug 11 13:35:03:   File "/usr/lib/python3.11/shutil.py", line 256, in copyfile
Aug 11 13:35:03:     with open(src, 'rb') as fsrc:
Aug 11 13:35:03:          ^^^^^^^^^^^^^^^
Aug 11 13:35:03: FileNotFoundError: [Errno 2] No such file or directory: 'data/template'
```

**Comment by nulqwy** [comment]
fixed\* as per 9298e0ee3f0e0f41002e8ef2c7c8c03aacb38502
\*now it shouldnt be the case, that server runs, but template folder doesnt exist
however it is still possible to get such error, if you delete the folder *after* the server has started, unlikely case tho
